version: '3'

services:
    nginx:
        image: nginx:1.19.0-alpine
        volumes:
            - ./backend:/usr/src/backend
            - ./dockerization/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./dockerization/logs:/var/log/nginx
        depends_on:
            - php
        links:
            - php
        ports:
            - "8100:80"
        networks:
            - financier

    php:
        build: ./dockerization/php
        volumes:
            - ./backend:/usr/src/backend
        ports:
            - '9002:9000'
        environment:
            DATABASE_URL: mysql://symfony:symfony@mysql:3306/financier?serverVersion=8
            XDEBUG_CONFIG: "remote_host=financier.local remote_enable=1 idekey=PHPSTORM"
            PHP_IDE_CONFIG: "serverName=financier.local"
        working_dir: /usr/src/backend
        env_file:
            - ./backend/.env
        user: 1000:1000
        depends_on:
            - mysql
        networks:
            - financier

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: financier
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - ./dockerization/mysql/data:/var/lib/mysql
        networks:
            - financier

    frontend:
        build:
            context: ./frontend
            dockerfile: ./../dockerization/frontend/Dockerfile
        volumes:
            - ./frontend:/usr/src/frontend
        links:
            - php
        networks:
            - financier
        ports:
            - '40190:8081'

networks:
    financier:
        driver: bridge