version: '3'

services:
  nginx:
    image: nginx:1.17
    hostname: financier.local
    container_name: financier_nginx
    volumes:
      - .:/usr/share/nginx/html
      - ./dockerization/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      financier:
        ipv4_address: 172.30.0.101

  php:
    build: ./dockerization/php
    container_name: financier_php
    user: 1000:1000
    volumes:
      - .:/usr/share/nginx/html
      - ./dockerization/composer/cache:/.composer/cache
      - ./dockerization/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=financier.local remote_enable=1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=financier.local"
    working_dir: /usr/share/nginx/html
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      financier:
        ipv4_address: 172.30.0.102

  mysql:
    image: mysql:8
    container_name: financier_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: financier
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./dockerization/mysql/data:/var/lib/mysql
    networks:
      financier:
        ipv4_address: 172.30.0.103

networks:
  financier:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/24